"""init felisdb for postgres

Revision ID: 759d9e49da39
Revises: 
Create Date: 2020-01-06 14:06:53.799446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759d9e49da39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('short_link', sa.String(length=80), nullable=True),
    sa.Column('full_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('short_link')
    )
    op.create_index(op.f('ix_pairs_unique_id'), 'pairs', ['unique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pairs_unique_id'), table_name='pairs')
    op.drop_table('pairs')
    # ### end Alembic commands ###
