e = Entry("f4dbdf21", "https://github.com/zilinglius")
db.session.add(e)
e = Entry("83dcefb7", "https://github.com/ddyasmile")
db.session.add(e)
e = Entry("1ad5be0d", "https://github.com/chris98122")
db.session.add(e)
e = Entry("6dd28e9b", "https://github.com/zhaoyang110157")
db.session.add(e)
e = Entry("f3b61b38", "https://github.com/xiaxiao2625666138")
db.session.add(e)
e = Entry("84b12bae", "https://github.com/yuetsin")
db.session.add(e)
e = Entry("1db87a14", "https://github.com/MaCoredroid")
db.session.add(e)
e = Entry("6abf4a82", "https://github.com/Dianaaaa")
db.session.add(e)
e = Entry("fa005713", "https://github.com/Diving-Fish")
db.session.add(e)
e = Entry("8d076785", "https://github.com/CodingYuanLiu")
db.session.add(e)
e = Entry("a15d25e1", "https://github.com/jinyuchencn")
db.session.add(e)
e = Entry("d65a1577", "https://github.com/sebastianj1w")
db.session.add(e)
e = Entry("4f5344cd", "https://github.com/wangtianxia-sjtu")
db.session.add(e)
e = Entry("3854745b", "https://github.com/tx19980520")
db.session.add(e)
e = Entry("a630e1f8", "https://github.com/eyeKill")
db.session.add(e)
e = Entry("d137d16e", "https://github.com/ZinuoCai")
db.session.add(e)
e = Entry("483e80d4", "https://github.com/2quarius")
db.session.add(e)
e = Entry("3f39b042", "https://github.com/Bert-Z")
db.session.add(e)
e = Entry("af86add3", "https://github.com/Girafboy")
db.session.add(e)
e = Entry("d8819d45", "https://github.com/sjyjytu")
db.session.add(e)
e = Entry("8a707622", "https://github.com/MrHate")
db.session.add(e)
e = Entry("fd7746b4", "https://github.com/Gusabary")
db.session.add(e)
e = Entry("647e170e", "https://github.com/EsdeathYZH")
db.session.add(e)
e = Entry("13792798", "https://github.com/Guozhi-explore")
db.session.add(e)
e = Entry("8d1db23b", "https://github.com/Yuan-Zhuo")
db.session.add(e)
e = Entry("fa1a82ad", "https://github.com/Veiasai")
db.session.add(e)
e = Entry("6313d317", "https://github.com/fyc1007261")
db.session.add(e)
e = Entry("1414e381", "https://github.com/CHIANGEL")
db.session.add(e)
e = Entry("84abfe10", "https://github.com/ruishaopu561")
db.session.add(e)
e = Entry("f3acce86", "https://github.com/zhaoshenglong")
db.session.add(e)
e = Entry("936b4763", "https://github.com/Yang-Xuanhui")
db.session.add(e)

db.session.commit()
exit
