apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\yuanz\Desktop\kompose-windows-amd64.exe convert -f .\docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  hostNetwork: true
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
