version : '3.5'
services:
  felisdb:
    image: yuxiqian/felis-catus-db:latest
    ports:
      - "5432:5432"
    container_name: felisdb
    healthcheck:
      test: ["CMD", "service postgresql restart", "echo -e \"\\q\" | sudo -u postgres psql"]
      timeout: 20s
      interval: 10s
      retries: 50
      start_period: 20s

  server:
    image: yuxiqian/felis-catus-server:latest
    ports:
      - "8080:8080"
    depends_on: ["felisdb"]
    container_name: server
    restart: always

