apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-c
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      schedulerName: custom-scheduler
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80