apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-customed
  labels:
    app: scheduler-customed
    component: scheduler
    tiler: control-plane
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-customed
      tiler: control-plane
      component: scheduler
  template:
    metadata:
      labels:
        app: scheduler-customed
        tiler: control-plane
        component: scheduler
    spec:
      serviceAccount: scheduler-customed
      containers:
      - name: scheduler-customed
        image: sonasingh46/custom-scheduler:v1.0
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false