apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: scheduler-customed 
  labels:
    app: scheduler-customed 
    component: scheduler-customed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-customed
subjects:
- kind: ServiceAccount
  name: scheduler-customed
  namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler