apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\yuanz\Desktop\kompose-windows-amd64.exe convert -f .\docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: server-custom
  name: server-custom
spec:
  selector:
    matchLabels:
      io.kompose.service: server-custom
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server-custom
    spec:
      schedulerName: scheduler-customed
      containers:
      - image: yuxiqian/felis-catus-server:latest
        name: server-custom
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}