apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\yuanz\Desktop\kompose-windows-amd64.exe convert -f .\docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: felisdb
  name: felisdb
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: felisdb
status:
  loadBalancer: {}
