name: Docker Image Build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: | 
        cd docker
        ./build_base_docker_github.sh
        ./build_docker_github.sh
        ./build_base_docker_dockerhub.sh
        ./build_docker_dockerhub.sh
